export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_OK = "GET_CHARACTERS_OK";
export const GET_CHARACTERS_FAIL = "GET_CHARACTERS_FAIL";

export const GET_CHARACTER = "GET_CHARACTER";
export const GET_CHARACTER_OK = "GET_CHARACTER_OK";
export const GET_CHARACTER_FAIL = "GET_CHARACTER_FAIL";
